namespace Querify.Models.Direct.Enums;

/// <summary>
/// Identifies who wrote a support conversation message.
/// </summary>
public enum MessageActorKind
{
    /// <summary>
    /// Message was written by the customer or end user requesting support.
    /// </summary>
    Contact = 1,

    /// <summary>
    /// Querify User
    /// </summary>
    User = 6,

    /// <summary>
    /// Message was generated by Direct automation.
    /// </summary>
    Automation = 11,

    /// <summary>
    /// Message was written by a human support agent.
    /// </summary>
    Agent = 16,

    /// <summary>
    /// Message was generated by the system to record operational context in the timeline.
    /// </summary>
    System = 21
}